development:
  cloud_name: unconventional
  api_key: '914771168565535'
  api_secret: RNiCYwr8ew2YuWqdstq_-eJkbvo
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: unconventional
  api_key: '914771168565535'
  api_secret: RNiCYwr8ew2YuWqdstq_-eJkbvo
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: unconventional
  api_key: '914771168565535'
  api_secret: RNiCYwr8ew2YuWqdstq_-eJkbvo
  enhance_image_tag: true
  static_image_support: false
